# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoC', models.CharField(choices=[('ENTRADA MANHA', 'ENTRADA MANHA'), ('SAIDA MANHA', 'SAIDA MANHA'), ('ENTRADA TARDE', 'ENTRADA TARDE'), ('SAIDA TARDE', 'SAIDA TARDE')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoF', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SAIDA', 'SAIDA')], max_length=7)),
                ('horaF', models.DateTimeField(auto_now=True)),
                ('ipF', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFu', models.CharField(max_length=128)),
                ('emailFu', models.CharField(max_length=128)),
                ('configuracaoFu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Configuracoes')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaH', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Justicativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.CharField(max_length=256)),
                ('Frequencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Frequencia')),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='chefeF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefeF', to='frequencia.Funcionario'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='funcionarioF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Funcionario'),
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='horarioC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Horario'),
        ),
    ]
