# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0004_auto_20171113_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes',
            name='tipoC',
            field=models.CharField(choices=[('ENTRADA MANHA', 'ENTRADA MANHA'), ('SAIDA MANHA', 'SAIDA MANHA'), ('ENTRADA TARDE', 'ENTRADA TARDE'), ('SAIDA TARDE', 'SAIDA TARDE')], max_length=20),
        ),
    ]
