# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0006_auto_20171113_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='configuracaoFu',
            field=models.ManyToManyField(to='frequencia.Configuracoes'),
        ),
    ]
