# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0007_auto_20171113_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='configuracaoFu',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='configuracaoFu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Configuracoes'),
        ),
    ]
