# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0008_auto_20171113_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='configuracaoFu',
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='funcionarioC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Funcionario'),
        ),
    ]
