# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0009_auto_20171113_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='justicativa',
            old_name='Frequencia',
            new_name='frequencia',
        ),
    ]
